### ISSUE TITLE
Missing arg in prepare CH() occasionally

### ISSUE THREAD

**Issue by litan1106** [tflanagan/php-quickbase#9]
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Too few arguments to function QuickBase\QuickBaseQuery::prepare
  CH(), 0 passed in home/code/vendor/tflanagan
  /quickbase/quickbase.php on line 385 and exactly 1 expected

**Comment by tflanagan** [comment]
Hey,

I've just released a patch that I believe will resolve this specific error, however I believe you reach this path in the code due to another underlying error (most likely a Quick Base error).

Let me know how v2.0.7 works for you.

Thanks.

Edit: I take that back, it is most likely a network issue, this path in the code is only reached when the curl request returns an empty string or is false.

**Comment by litan1106** [comment]
Thanks for the quick fix.
